import type { Metadata } from "next";

export const siteName = "ProVision Support Services CIC";

export const siteUrl = (
  process.env.NEXT_PUBLIC_SITE_URL || "https://www.provisionsupportservice.co.uk"
).replace(/\/+$/, "");

export const defaultTitle = `${siteName} | Supported Accommodation in Coventry`;

export const defaultDescription =
  "ProVision Support Services CIC provides supported accommodation and person-centred support across Coventry. We help people sustain a tenancy, build life skills and move toward independent living. Referrals welcome.";

// Shared Open Graph fields. Next.js merges metadata shallowly, so a page that
// sets `openGraph` must repeat these or they are dropped (including the
// default image generated by src/app/opengraph-image.tsx).
export const baseOpenGraph = {
  siteName,
  locale: "en_GB",
  type: "website",
  images: [
    {
      url: "/opengraph-image",
      width: 1200,
      height: 630,
      alt: `${siteName}: supported accommodation in Coventry`,
    },
  ],
} satisfies Metadata["openGraph"];

export const absoluteUrl = (path: string) => new URL(path, siteUrl).toString();

type PageMetadataInput = {
  /** Page title without the site name (the root title template adds it). */
  title: string;
  description: string;
  /** Route path, e.g. "/about". */
  path: string;
};

export function pageMetadata({
  title,
  description,
  path,
}: PageMetadataInput): Metadata {
  const fullTitle = `${title} | ${siteName}`;

  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: { ...baseOpenGraph, title: fullTitle, description, url: path },
    twitter: { card: "summary_large_image", title: fullTitle, description },
  };
}

// ---- Structured data (JSON-LD) ----

export const organizationId = `${siteUrl}/#organization`;

export const organizationJsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  "@id": organizationId,
  name: siteName,
  alternateName: "ProVision CIC",
  url: siteUrl,
  logo: absoluteUrl("/img/primary-logo.png"),
  description: defaultDescription,
  email: "info@provisionsupportservice.co.uk",
  telephone: "+44 7828 887031",
  address: {
    "@type": "PostalAddress",
    streetAddress: "32 Hazelville Road",
    addressLocality: "Birmingham",
    postalCode: "B28 9QF",
    addressCountry: "GB",
  },
  areaServed: { "@type": "City", name: "Coventry" },
  contactPoint: [
    {
      "@type": "ContactPoint",
      contactType: "customer service",
      email: "info@provisionsupportservice.co.uk",
      telephone: "+44 7828 887031",
      areaServed: "GB",
      availableLanguage: "en-GB",
    },
    {
      "@type": "ContactPoint",
      contactType: "referrals",
      email: "referrals@provisionsupportservice.co.uk",
      telephone: "+44 7581 467406",
      areaServed: "GB",
      availableLanguage: "en-GB",
    },
  ],
  sameAs: [
    "https://www.linkedin.com/company/provision-support-services-cic/",
    "https://twitter.com/ProVisionCIC",
    "https://www.instagram.com/provisioncic/",
  ],
};

/** Home → … → current page. Each item is `[name, path]`. */
export function breadcrumbJsonLd(items: [name: string, path: string][]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [["Home", "/"] as const, ...items].map(
      ([name, path], index) => ({
        "@type": "ListItem",
        position: index + 1,
        name,
        item: absoluteUrl(path),
      }),
    ),
  };
}
